apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  JWT_SECRET: cGFyYW1zY2Vk # base64 encoded value of "random#secret"
  STRIPE_SECRET_KEY: c2tfdGVzdF8xU01TUGFQNmYxQXFYZ0ZJWi1aMEtYQm5LVmNlMA== # base64 encoded Stripe key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGODB_URI: "mongodb+srv://arangarajan:arangarajan@cluster0.r8rzl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  PORT: "4000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jonathan02/tomato:backend
          ports:
            - containerPort: 4000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: STRIPE_SECRET_KEY
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGODB_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
  type: ClusterIP
